-- Creazione Tabella Operazioni
create table burns (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null, -- Nome operazione (es. "Intervento Orgosolo Sett1")
  status text default 'planning', -- planning, active, completed
  location_name text,
  -- Dati Geografici (GeoJSON)
  area_geojson jsonb, 
  -- Dati Tecnici (Snapshot)
  weather_data jsonb,
  fuel_model text,
  risk_level text,
  -- Report
  ai_report text,
  pdf_url text
);

-- Abilita Row Level Security (RLS) per sicurezza
alter table burns enable row level security;

-- Policy: Solo gli utenti autenticati possono leggere/scrivere i loro dati
create policy "Users can view own burns" on burns for select using (auth.uid() = user_id);
create policy "Users can insert own burns" on burns for insert with check (auth.uid() = user_id);
create policy "Users can update own burns" on burns for update using (auth.uid() = user_id);
